# -*- coding: utf-8 -*-
"""Lab_3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vR8Q1PO4i1q5n5F2Ay2QCzEN4rkpw2de
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import fetch_covtype
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)
print("Loading Covertype dataset...")
data = fetch_covtype()

X = data.data
y = data.target

print("Dataset shape:", X.shape)
print("Number of classes:", len(np.unique(y)))

# Convert classes from 1-7 to 0-6
y = y - 1

classes, counts = np.unique(y, return_counts=True)

print("\nClass distribution:")
for c, count in zip(classes, counts):
    print(f"Class {c}: {count}")

plt.figure(figsize=(8, 5))
plt.bar(classes, counts)
plt.xlabel("Class")
plt.ylabel("Number of Samples")
plt.title("Class Distribution")
plt.show()

num_classes = 7

Y = np.zeros((len(y), num_classes))
Y[np.arange(len(y)), y] = 1

X_train, X_temp, Y_train, Y_temp, y_train, y_temp = train_test_split(X,Y,y,test_size=0.20,random_state=42,stratify=y)
X_val, X_test, Y_val, Y_test, y_val, y_test = train_test_split( X_temp,Y_temp,y_temp,test_size=0.50,random_state=42,stratify=y_temp)

print("\nData split:")
print("Training:", X_train.shape)
print("Validation:", X_val.shape)
print("Testing:", X_test.shape)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)


N = len(y_train)
K = num_classes

class_counts = np.bincount(y_train)

class_weights = N / (K * class_counts)

print("\nClass weights:")
for i, weight in enumerate(class_weights):
    print(f"Class {i}: {weight:.4f}")

def relu(z):
    return np.maximum(0, z)


def relu_derivative(z):
    return (z > 0).astype(float)


def softmax(z):
    z = z - np.max(z, axis=1, keepdims=True)

    exp_z = np.exp(z)

    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

input_size = 54
hidden1 = 64
hidden2 = 32
hidden3 = 16
output_size = 7

np.random.seed(42)

W1 = np.random.randn(input_size, hidden1) * np.sqrt(2 / input_size)
b1 = np.zeros((1, hidden1))

W2 = np.random.randn(hidden1, hidden2) * np.sqrt(2 / hidden1)
b2 = np.zeros((1, hidden2))

W3 = np.random.randn(hidden2, hidden3) * np.sqrt(2 / hidden2)
b3 = np.zeros((1, hidden3))

W4 = np.random.randn(hidden3, output_size) * np.sqrt(2 / hidden3)
b4 = np.zeros((1, output_size))

def forward(X):

    Z1 = X @ W1 + b1
    A1 = relu(Z1)

    Z2 = A1 @ W2 + b2
    A2 = relu(Z2)

    Z3 = A2 @ W3 + b3
    A3 = relu(Z3)

    Z4 = A3 @ W4 + b4
    Y_hat = softmax(Z4)

    cache = (Z1, A1, Z2, A2, Z3, A3, Z4, Y_hat)

    return Y_hat, cache

def compute_loss(Y, Y_hat):

    epsilon = 1e-12

    Y_hat = np.clip(Y_hat, epsilon, 1 - epsilon)

    true_classes = np.argmax(Y, axis=1)

    sample_weights = class_weights[true_classes]

    loss = -np.sum(
        sample_weights * np.sum(Y * np.log(Y_hat), axis=1)
    ) / len(Y)

    return loss

def backward(X, Y, cache):

    global W1, b1, W2, b2, W3, b3, W4, b4

    Z1, A1, Z2, A2, Z3, A3, Z4, Y_hat = cache

    batch_size = X.shape[0]
    true_classes = np.argmax(Y, axis=1)

    sample_weights = class_weights[true_classes]
    dZ4 = (Y_hat - Y) * sample_weights[:, None]

    dZ4 /= batch_size

    dW4 = A3.T @ dZ4
    db4 = np.sum(dZ4, axis=0, keepdims=True)

    dA3 = dZ4 @ W4.T

    dZ3 = dA3 * relu_derivative(Z3)

    dW3 = A2.T @ dZ3
    db3 = np.sum(dZ3, axis=0, keepdims=True)


    # Hidden Layer 2


    dA2 = dZ3 @ W3.T

    dZ2 = dA2 * relu_derivative(Z2)

    dW2 = A1.T @ dZ2
    db2 = np.sum(dZ2, axis=0, keepdims=True)


    # Hidden Layer 1


    dA1 = dZ2 @ W2.T

    dZ1 = dA1 * relu_derivative(Z1)

    dW1 = X.T @ dZ1
    db1 = np.sum(dZ1, axis=0, keepdims=True)

    return dW1, db1, dW2, db2, dW3, db3, dW4, db4

def update_parameters(
    gradients,
    learning_rate
):

    global W1, b1, W2, b2, W3, b3, W4, b4

    dW1, db1, dW2, db2, dW3, db3, dW4, db4 = gradients

    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1

    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2

    W3 -= learning_rate * dW3
    b3 -= learning_rate * db3

    W4 -= learning_rate * dW4
    b4 -= learning_rate * db4


# 13. PREDICTION FUNCTION


def predict(X):

    Y_hat, _ = forward(X)

    return np.argmax(Y_hat, axis=1)


# 14. TRAINING


learning_rate = 0.01
batch_size = 128
epochs = 100

patience = 15

best_val_loss = float("inf")
patience_counter = 0

train_losses = []
val_losses = []

train_accuracies = []
val_accuracies = []

num_samples = X_train.shape[0]

print("\nStarting training...\n")

for epoch in range(epochs):

    # Shuffle training data
    indices = np.random.permutation(num_samples)

    X_train_shuffled = X_train[indices]
    Y_train_shuffled = Y_train[indices]

    # Mini-batch training
    for start in range(0, num_samples, batch_size):

        end = start + batch_size

        X_batch = X_train_shuffled[start:end]
        Y_batch = Y_train_shuffled[start:end]

        # Forward propagation
        Y_hat, cache = forward(X_batch)

        # Backpropagation
        gradients = backward(
            X_batch,
            Y_batch,
            cache
        )

        # Update weights
        update_parameters(
            gradients,
            learning_rate
        )


    # Training loss


    train_predictions, _ = forward(X_train)

    train_loss = compute_loss(
        Y_train,
        train_predictions
    )

    train_pred_classes = np.argmax(
        train_predictions,
        axis=1
    )

    train_accuracy = accuracy_score(
        y_train,
        train_pred_classes
    )


    # Validation loss


    val_predictions, _ = forward(X_val)

    val_loss = compute_loss(
        Y_val,
        val_predictions
    )

    val_pred_classes = np.argmax(
        val_predictions,
        axis=1
    )

    val_accuracy = accuracy_score(
        y_val,
        val_pred_classes
    )

    train_losses.append(train_loss)
    val_losses.append(val_loss)

    train_accuracies.append(train_accuracy)
    val_accuracies.append(val_accuracy)

    print(
        f"Epoch {epoch + 1:3d}/{epochs} | "
        f"Train Loss: {train_loss:.4f} | "
        f"Val Loss: {val_loss:.4f} | "
        f"Train Acc: {train_accuracy:.4f} | "
        f"Val Acc: {val_accuracy:.4f}"
    )


    # Early stopping


    if val_loss < best_val_loss:

        best_val_loss = val_loss
        patience_counter = 0

        best_W1 = W1.copy()
        best_b1 = b1.copy()

        best_W2 = W2.copy()
        best_b2 = b2.copy()

        best_W3 = W3.copy()
        best_b3 = b3.copy()

        best_W4 = W4.copy()
        best_b4 = b4.copy()

    else:

        patience_counter += 1

        if patience_counter >= patience:

            print("\nEarly stopping triggered.")

            break


# 15. RESTORE BEST MODEL


W1 = best_W1
b1 = best_b1

W2 = best_W2
b2 = best_b2

W3 = best_W3
b3 = best_b3

W4 = best_W4
b4 = best_b4


# 16. TEST PREDICTION


test_probabilities, _ = forward(X_test)

y_pred = np.argmax(
    test_probabilities,
    axis=1
)


# 17. EVALUATION


accuracy = accuracy_score(
    y_test,
    y_pred
)

precision = precision_score(
    y_test,
    y_pred,
    average="macro",
    zero_division=0
)

recall = recall_score(
    y_test,
    y_pred,
    average="macro",
    zero_division=0
)

f1 = f1_score(
    y_test,
    y_pred,
    average="macro",
    zero_division=0
)

print("FINAL TEST RESULTS")

print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")


# 18. CLASSIFICATION REPORT


print("\nClassification Report:\n")

print(
    classification_report(
        y_test,
        y_pred,
        zero_division=0
    )
)


# 19. CONFUSION MATRIX


cm = confusion_matrix(
    y_test,
    y_pred
)

plt.figure(figsize=(9, 7))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.xlabel("Predicted Class")
plt.ylabel("True Class")
plt.title("7 × 7 Confusion Matrix")

plt.show()


# 20. TRAINING LOSS CURVE


plt.figure(figsize=(8, 5))

plt.plot(
    train_losses,
    label="Training Loss"
)

plt.plot(
    val_losses,
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training and Validation Loss")

plt.legend()

plt.show()


# 21. ACCURACY CURVE


plt.figure(figsize=(8, 5))

plt.plot(
    train_accuracies,
    label="Training Accuracy"
)

plt.plot(
    val_accuracies,
    label="Validation Accuracy"
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Training and Validation Accuracy")

plt.legend()

plt.show()

# 22. PER-CLASS F1 SCORE


class_f1 = f1_score(
    y_test,
    y_pred,
    average=None,
    zero_division=0
)

plt.figure(figsize=(8, 5))

plt.bar(
    range(num_classes),
    class_f1
)

plt.xlabel("Class")
plt.ylabel("F1 Score")
plt.title("Per-Class F1 Score")

plt.xticks(range(num_classes))

plt.show()


# 23. TRUE VS PREDICTED CLASS DISTRIBUTION


true_counts = np.bincount(
    y_test,
    minlength=num_classes
)

pred_counts = np.bincount(
    y_pred,
    minlength=num_classes
)

x = np.arange(num_classes)
width = 0.35

plt.figure(figsize=(9, 5))

plt.bar(
    x - width / 2,
    true_counts,
    width,
    label="True"
)

plt.bar(
    x + width / 2,
    pred_counts,
    width,
    label="Predicted"
)

plt.xlabel("Class")
plt.ylabel("Number of Samples")
plt.title("True vs Predicted Class Distribution")

plt.xticks(x)

plt.legend()

plt.show()